/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as CadastrosRouteImport } from './routes/cadastros'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRoleRouteImport } from './routes/login.$role'

const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosRoute = CadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoleRoute = LoginRoleRouteImport.update({
  id: '/login/$role',
  path: '/login/$role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/manutencao': typeof ManutencaoRoute
  '/planejamento': typeof PlanejamentoRoute
  '/login/$role': typeof LoginRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/manutencao': typeof ManutencaoRoute
  '/planejamento': typeof PlanejamentoRoute
  '/login/$role': typeof LoginRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/manutencao': typeof ManutencaoRoute
  '/planejamento': typeof PlanejamentoRoute
  '/login/$role': typeof LoginRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastros'
    | '/manutencao'
    | '/planejamento'
    | '/login/$role'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastros' | '/manutencao' | '/planejamento' | '/login/$role'
  id:
    | '__root__'
    | '/'
    | '/cadastros'
    | '/manutencao'
    | '/planejamento'
    | '/login/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrosRoute: typeof CadastrosRoute
  ManutencaoRoute: typeof ManutencaoRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  LoginRoleRoute: typeof LoginRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros': {
      id: '/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof CadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$role': {
      id: '/login/$role'
      path: '/login/$role'
      fullPath: '/login/$role'
      preLoaderRoute: typeof LoginRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrosRoute: CadastrosRoute,
  ManutencaoRoute: ManutencaoRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  LoginRoleRoute: LoginRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
